// heroes sorted by their heroid
const char *heroes[] = {
    "antimage",
    "axe",
    "bane",
    "bloodseeker",
    "crystal maiden",
    "drow ranger",
    "earthshaker",
    "juggernaut",
    "mirana",
    "morphling",
    "nevermore",
    "phantom lancer",
    "puck",
    "pudge",
    "razor",
    "sand king",
    "storm spirit",
    "sven",
    "tiny",
    "vengefulspirit",
    "windrunner",
    "zuus",
    "kunkka",
    "lina",
    "lion",
    "shadow shaman",
    "slardar",
    "tidehunter",
    "witch doctor",
    "lich",
    "riki",
    "enigma",
    "tinker",
    "sniper",
    "necrolyte",
    "warlock",
    "beastmaster",
    "queenofpain",
    "venomancer",
    "faceless void",
    "skeleton king",
    "death prophet",
    "phantom assassin",
    "pugna",
    "templar assassin",
    "viper",
    "luna",
    "dragon knight",
    "dazzle",
    "rattletrap",
    "leshrac",
    "furion",
    "life stealer",
    "dark seer",
    "clinkz",
    "omniknight",
    "enchantress",
    "huskar",
    "night stalker",
    "broodmother",
    "bounty hunter",
    "weaver",
    "jakiro",
    "batrider",
    "chen",
    "spectre",
    "ancient apparition",
    "doom bringer",
    "ursa",
    "spirit breaker",
    "gyrocopter",
    "alchemist",
    "invoker",
    "silencer",
    "obsidian destroyer",
    "lycan",
    "brewmaster",
    "shadow demon",
    "lone druid",
    "chaos knight",
    "meepo",
    "treant",
    "ogre magi",
    "undying",
    "rubick",
    "disruptor",
    "nyx assassin",
    "naga siren",
    "keeper of the light",
    "wisp",
    "visage",
    "slark",
    "medusa",
    "troll warlord",
    "centaur",
    "magnataur",
    "shredder",
    "bristleback",
    "tusk",
    "skywrath mage",
    "abaddon",
    "elder titan",
    "legion commander",
    "techies",
    "ember spirit",
    "earth spirit",
    "abyssal underlord",
    "terrorblade",
    "phoenix",
    "oracle",
    "winter wyvern",
    "arc warden",
    "monkey king",
    "dark willow",
    "pangolier",
    "grimstroke",
};
